apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: colab-pvc
  namespace: colab-llm-cpu
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 200Gi 
