apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: colab-pvc-ssd
  namespace: colab-llm-cpu
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-rwo
  resources:
    requests:
      storage: 300Gi 
