apiVersion: v1
kind: Service
metadata:
  name: colab-runtime-service
  namespace: colab-llm-cpu
spec:
  selector:
    app: colab-runtime
  ports:
  - port: 9000
    targetPort: 8080
    protocol: TCP  
